import os
import sys
import rtconfig

Import('rtconfig')
Import('BSP_ROOT')

from building import *

cwd = GetCurrentDir()

# add the include path.
path = Split("""
""")

# add the general drivers.
src = Split("""
""")

# add pin drivers.
if GetDepend('BSP_USING_SPI_FLASH'):
    src += [
        cwd + '/w25qxx/src/driver_w25qxx.c',
        cwd + '/w25qxx/example/driver_w25qxx_basic.c',
        cwd + '/w25qxx/example/driver_w25qxx_advance.c',
        cwd + '/w25qxx_port/driver_w25qxx_interface.c',
        ]
    path += [
        cwd + '/w25qxx/src',
        cwd + '/w25qxx/interface',
        cwd + '/w25qxx/example',
        cwd + '/w25qxx_port'
        ]

group = DefineGroup('Board/libraries', src, depend = [''], CPPPATH = path)

Return('group')
